# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    restart: no 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    network_mode: "host"

  mongo-express:
    container_name: mongo-frontend
    image: mongo-express
    restart: no 
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 
      ME_CONFIG_MONGODB_URL: mongodb://root:example@127.0.0.1:27017/
      ME_CONFIG_BASICAUTH: false
    network_mode: "host"
